Draft: Added getting started guide for react native
MapsPeople/docsite pull request #116
Opened 2023-07-25 10:54 UTC by timMikkelsen

2023-08-01 12:19 UTC, casm-mp requested changes
docsite
* folder name space -> %20, use hyphen-seperated-name instead?
* should the files be numbered? It is ignored in the url, but easier to get an overview.

In general:
* maybe mention *where* to insert the code, so that we will get the same order when comparing with the complete version of the getting started project.
* Make sure the text describes why and what to change.
* App.tsx - remove comment about order of screens

end result:
* direction steps not shown on Android
* not properly switching between instruction steps

2023-08-01 13:00 UTC, casm-mp commented on docs/01-getting-started/React Native/getting-directions.mdx
> +  getRoute: () => void;
from/toLocation and getRoute should probably be present in the basic code

2023-08-01 13:03 UTC, casm-mp commented on docs/01-getting-started/React Native/livedata.mdx
> +Enabling Live Data through [`MapControl`](https://app.mapsindoors.com/mapsindoors/reference/react-native/google-maps/1.0.0/classes/MapControl.html) is as simple as calling [`mapControl.enableLiveData
These links show the markdown syntax instead.

2023-08-01 13:04 UTC, casm-mp commented on docs/01-getting-started/React Native/livedata.mdx
> +<img src="/img/getting-started/android_live_data_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
We should update the video to be of the react native implementation

2023-08-01 13:05 UTC, casm-mp commented on docs/01-getting-started/React Native/getting-directions.mdx
Some code is introduced, then changed further down:
	* Bottomsheet gets onClose added later.
	* Changed so it shows either instructions or results depending on which is available
	— The UI part is probably not as important, and we should focus on describing how we get the directions. So maybe we can just provide the final version to begin with.

2023-08-04 13:04 UTC, timMikkelsen commented on docs/01-getting-started/React Native/project-setup.mdx
> +```
Made a clearer seperation of the basic/manual setup.
npm install/pod install is described in the readme of the code projects. As mentioned in the step for the basic example.
Pager view is not used in the project.

2023-08-04 13:05 UTC, timMikkelsen commented on docs/01-getting-started/React Native/search.mdx
> +The components have already been made, but we need to fill in some data to show our search results from the `MPLocation`. The SearchBox is just a simple input field with two buttons, to call our sear
Added more description to these steps now

2023-08-04 13:06 UTC, timMikkelsen commented on docs/01-getting-started/React Native/search.mdx
> +        <Button title={'Cancel'} onPress={() => onSearch(undefined)}/>
It is now present in the basic example code

2023-08-04 13:06 UTC, timMikkelsen commented on docs/01-getting-started/React Native/search.mdx
Added more detail to where to insert cod, in gerneral

2023-08-04 13:07 UTC, timMikkelsen commented on docs/01-getting-started/React Native/display-a-map.mdx
More descriptive now

2023-08-04 13:07 UTC, timMikkelsen commented on docs/01-getting-started/React Native/display-a-map.mdx
> +      }}/>
Empty bottom sheet is now a part of the code example

2023-08-07 07:19 UTC, timMikkelsen commented on docs/01-getting-started/React Native/getting-directions.mdx
> +  getRoute: () => void;
It is specifically explained, so no need.

2023-08-07 07:21 UTC, timMikkelsen commented on docs/01-getting-started/React Native/getting-directions.mdx
Code changes are explained specifically now

2023-08-07 07:25 UTC, timMikkelsen commented
> docsite
> 
> * folder name space -> %20, use hyphen-seperated-name instead?
> * should the files be numbered? It is ignored in the url, but easier to get an overview.
> 
> In general:
> 
> * maybe mention _where_ to insert the code, so that we will get the same order when comparing with the complete version of the getting started project.
> * Make sure the text describes why and what to change.
> * App.tsx - remove comment about order of screens
> 
> end result:
> 
> * direction steps not shown on Android
> * not properly switching between instruction steps

Keeping the same naming as for every other folder.
We'll keep them as is for now

More specifically mentioned where to insert code, will not mention specific order/lines as it is not necessary in my opinion, and files are small enough that a manual comparison should be sufficient. 
Done

end results part was addressed in office...

2023-08-07 11:09 UTC, casm-mp requested changes
Smaller comments.

Also maybe change the folder name to 'react-native' to match the other guides, and avoids a %20 in the url.

2023-08-07 11:52 UTC, casm-mp approved these changes

2023-08-11 08:13 UTC, matiasholst approved these changes

2023-08-11 08:16 UTC, merged