Ios migration guide
MapsPeople/docsite pull request #45
Opened 2023-03-17 12:24 UTC by fasaMaps

Added/updated needed changes.

Note: 
- Missing v4 specific link to both refernce documentation and manual download SDK missing

2023-03-21 14:36 UTC, ChristianWolf-mapspeople requested changes
It would be great to update the syntax to more modern Swift (e.g. no need for `.init()` and data type annotation in many places).

The code snippets should also be valid, which many of them are not. I have tried to point out where they are not, but I may have missed some.

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/set-up-your-environment.mdx
> +        }
Indent consistently – maybe use Xcode to reformat

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +
This should be alleviated in v4, so no need to mention here any longer.

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +In order to accomplish this we will be utilising the [MPMapControl Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v3/interface_m_p_map_control.html). Open the file, `ViewController.swif
```suggestion
In order to accomplish this we will be utilising the [MPMapControl Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpmapcontrol). Open the file, `ViewController.swift` and, once again, add in the following import statements to the top of the file,
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +import MapsIndoors
```suggestion
import MapsIndoorsCore
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +import MapsIndoors
```suggestion
import MapsIndoorsCore
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +The [MPMapControl Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v3/interface_m_p_map_control.html) the is connective class between the Map Engine(either Google Maps or Mapbox) and the
```suggestion
The [MPMapControl Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpmapcontrol) is the connective class between the Map Engine (either Google Maps or Mapbox) and MapsIndoors. It allows the two services to collaborate by overlaying the MapsIndoors information on the Map Engine information.
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +*Note: This also means logic is appended onto many Google Maps listeners, which means that using Google Maps listeners directly might break intended behavior of the MapsIndoors experience. We recomme
Must also mention Mapbox

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +*Note: This also means logic is appended onto many Google Maps listeners, which means that using Google Maps listeners directly might break intended behavior of the MapsIndoors experience. We recomme
```suggestion
*Note: This also means logic is appended onto many Google Maps listeners, which means that using Google Maps listeners directly might break intended behavior of the MapsIndoors experience. We recommend checking our [reference docs](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors), and see if you can add a specific `Listener` through `MPMapControl`. If this is possible, it is highly recommend you do so.*
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +Running the app wihtout the use of code aobve indeed displays a map, however this is through the use of the Map Engine of your choice exclusively and with a default map region displayed. But we used
```suggestion
Running the app without the use of code above indeed displays a map, however this is only using the Map Engine of your choice and with a default map region displayed. But we want to use MapsIndoors to showcase a specific location.
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +We have now added a *very* simple search feature! Running the app now should yield a combined map of The White House, showing both the external and internal geographical information. However, let us
This seems kind of out of place…

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +Afterwards, we set-up a Query and Filter based on the [MPQuery Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v3/interface_m_p_query.html#a9da8ff62b6d17e45403b9005c73e811f) and [MPFilte
```suggestion
Afterwards, we set up a Query and Filter based on the [MPQuery Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpquery) and [MPFilter Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpfilter) classes respectively, these serve as our search specifications.
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +Finally, the [MPLocationService Class](https://app.mapsindoors.com/mapsindoors/reference/ios/v3/interface_m_p_location_service.html#a140844121a239dcf1709210e1723c312) enables us to search through the
MPLocationService is no longer used directly. Instead, MPMapsIndoors.shared.locationsWith(query:filter:) is used.
Please rephrase paragraph.

Link to ref docs: https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mapsindoorsshared/locationswith(query:filter:)

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +import MapsIndoors
```suggestion
import MapsIndoorsCore
import MapsIndoorsGoogleMaps
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +    var currentAuthorizationFlow: OIDExternalUserAgentSession?
Too much copied directly from our Demos app 😄 
```suggestion
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +        GMSServices.provideAPIKey(AppDelegate.gApiKey)
We have not mentioned `AppDelegate.gApiKey` so we should not make use of it here (even if we do in our Demos app)

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +        let location = CLLocationCoordinate2D(latitude: 57.057964, longitude: 9.9504112)
The `location` var is never used
```suggestion
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/display-a-map.mdx
> +import MapsIndoors
```suggestion
import MapsIndoorsCore
import MapsIndoorsMapbox
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +Our goal now is to enable the user to interact with a search bar and move the map with respect to their search. Therefore, we need to implement a bit more functionality into our ViewController class,
```suggestion
Our goal now is to enable the user to interact with a search bar and move the map with respect to their search. Therefore, we need to implement a bit more functionality into our ViewController class, so feel free to update it as follows.
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +lazy var destinationSearch:UISearchBar = UISearchBar.init(frame: CGRect.init(x: 0, y: 40, width: 0, height: 0))
```suggestion
lazy var destinationSearch:UISearchBar = UISearchBar(frame: CGRect(x: 0, y: 40, width: 0, height: 0))
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +var tableView = UITableView.init(frame: CGRect.init(x: 0, y: 90, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
```suggestion
var tableView = UITableView(frame: CGRect(x: 0, y: 90, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +tableView.delegate = self
Indentation missing

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +    let filter = MPFilter.init()
```suggestion
    let query = MPQuery()
    let filter = MPFilter()
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +            self.tableView.reloadData()
Too much indentation

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/search.mdx
> +    let cell = UITableViewCell.init()
```suggestion
    let cell = UITableViewCell()
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
This needs the content @fhansenMP has written somewhere…

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +In a lot of cases, the user might not want to display a specific region, but rather get a route proposed that will lead them to where they need to go. In order to accomplish this, we utilize the [MPD
```suggestion
In a lot of cases, the user might not want to display a specific region, but rather get a route proposed that will lead them to where they need to go. In order to accomplish this, we utilize the [MPDirectionsService](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpdirectionsservice) class, which we will be able to query using the [MPDirectionsQuery](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpdirectionsquery) class, while to actually display the result we use the [MPDirectionsRenderer](https://app.mapsindoors.com/mapsindoors/reference/ios/v4-doc/documentation/mapsindoors/mpdirectionsrenderer).
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +var origin:MPPoint = MPPoint(lat: 38.897382, lon: -77.037447, zValue:0)
```suggestion
var origin= MPPoint(latitude: 38.897382, longitude: -77.037447, z: 0)
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +var destination:MPPoint = MPPoint.init()
```suggestion
var destination= MPPoint()
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +private let renderer = MPDirectionsRenderer()
```suggestion
private let renderer = mapControl.newDirectionsRenderer()
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +        self.mapControl?.go(to: location)
You should try the snippets in Xcode
```suggestion
        let location = searchResult![indexPath.row]
        self.destination = location.position
        self.mapControl?.goTo(location)
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/directions.mdx
> +    let directions = MPDirectionsService()
```suggestion
    let directions = MPMapsIndoors.shared.directionsService
```

2023-03-21 14:36 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/live-data.mdx
> +Learn more about about controlling and rendering Live Data in MapsIndoors in the [introducion to Live Data](/live-data-intro/)
```suggestion
Learn more about about controlling and rendering Live Data in MapsIndoors in the [introduction to Live Data](/live-data-intro/)
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople requested changes
The migration guide has many links to the Android Getting Started Guide. I suspect they should be pointing to the iOS version…

There are still a number of comments from previous review that need to be addressed.

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +MapsIndoors SDK Map Engine Flavors[​](https://docsite.mapsindoors.com/getting-started/android/v4/#mapsindoors-sdk-map-engine-flavors)
References Android Getting Started Guide – is this on purpose?

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +```swift
```suggestion
```ruby
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +```swift
```suggestion
```ruby
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +MapsIndoors Initialization[​](https://docsite.mapsindoors.com/getting-started/android/v4/#mapsindoors-initialization) & Usage
References Android Getting Started Guide – is this on purpose?

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +let error = await MPMapsIndoors.shared.load(apiKey: "YOUR_MAPSINDOORS_API_KEY")
```suggestion
do {
    try await MPMapsIndoors.shared.load(apiKey: "YOUR_MAPSINDOORS_API_KEY")
} catch {
    // Do something with the thrown error
    print(error)
}
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +Note that this is async/await and therefore requires an asynchronous context, and returns a potential loading error. You can therefore be sure on the next line, that the SDK has either successfully l
```suggestion
Note that this is async/await and therefore requires an asynchronous context, and potentially throws an error if there were problems during loading MapsIndoors data. You can therefore be sure on the next line, that the SDK has either successfully loaded, or failed.
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +let mapConfig = MPMapConfig.init(gmsMapView: googleMapsView, googleApiKey: "AIza....")
```suggestion
let mapConfig = MPMapConfig(gmsMapView: googleMapsView, googleApiKey: "AIza....")
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +let mapConfig = MPMapConfig.init(mapBoxView: mapboxMapView, accessToken: "mapbox api key")
```suggestion
let mapConfig = MPMapConfig(mapBoxView: mapboxMapView, accessToken: "mapbox api key")
```

2023-03-31 08:13 UTC, ChristianWolf-mapspeople commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +    if let displayRule = MPMapsIndoors.shared.disPplayRuleFor(location: location) {
```suggestion
    if let displayRule = MPMapsIndoors.shared.displayRuleFor(location: location) {
```

2023-03-31 09:19 UTC, fhansenMP commented on docs/01-getting-started/ios/v4/v4-migration-guide.mdx
> +MapsIndoors Initialization[​](https://docsite.mapsindoors.com/getting-started/android/v4/#mapsindoors-initialization) & Usage
nope, error - fixing all urls to 'ios' instead of 'android'

2023-03-31 12:04 UTC, ChristianWolf-mapspeople approved these changes

2023-03-31 12:06 UTC, merged