set up Flutter folder
MapsPeople/docsite pull request #61
Opened 2023-04-28 11:06 UTC by JG1995

2023-08-14 08:21 UTC, casm-mp requested changes
- Few comments on the content.
- Missing iOS sections of the guide
- Also a bunch of links that need to be updated or added.
- Result videos need to be updated

2023-08-14 08:21 UTC, casm-mp commented on docs/01-getting-started/flutter/directions.mdx
> +With this we now have a class that will handle creating a Route and displaying it on the map for us. You can see the entire implementation of RouteHandler here: [main.dart](example.com)
Also update this link

2023-08-14 08:21 UTC, casm-mp commented on docs/01-getting-started/flutter/directions.mdx
> +<img src="/img/getting-started/android_directions_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
Replace gif with flutter version

2023-08-14 08:21 UTC, casm-mp commented on docs/01-getting-started/flutter/livedata.mdx
> +<img src="/img/getting-started/android_live_data_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
Replace gif with flutter version

2023-08-14 08:21 UTC, casm-mp commented on docs/01-getting-started/flutter/search.mdx
> +When you are done showing the search results you can [call `clearFliter()`](example.com).
Links.

2023-08-14 08:21 UTC, casm-mp commented on docs/01-getting-started/flutter/search.mdx
> +Create a search method that takes a search string as a parameter in your `State` class. In this example we only use the [`setTake` on the `MPFilter`](https://app.mapsindoors.com/mapsindoors/reference
Link should be updated to something relevant for the flutter implementation.

2023-08-14 12:30 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +With this we now have a class that will handle creating a Route and displaying it on the map for us. You can see the entire implementation of RouteHandler here: [main.dart](example.com)
Will fix when v2 and the guide app has been released

2023-08-14 12:38 UTC, matiasholst commented on docs/01-getting-started/flutter/livedata.mdx
> +Enabling Live Data through [`MapsIndoorsWidget`](example.com) is as simple as [calling `mapsindoorsWidget.enableLiveData()`](example.com) with a [Domain Type](example.com).
Will fix when v2 and the guide app has been released

2023-08-14 12:38 UTC, matiasholst commented on docs/01-getting-started/flutter/map.mdx
> +See the full example of MapsActivity here: [MapsActivity.java](https://github.com/MapsPeople/MapsIndoors-Android-Examples/tree/main/Google_Maps/mapsindoorsgettingstartedjava) or [MapsActivity.kt](htt
Will fix when v2 and the guide app has been released

2023-08-14 12:39 UTC, matiasholst commented on docs/01-getting-started/flutter/new-project.mdx
> +The Mapbox basic example is located here:  [Java](https://github.com/MapsPeople/MapsIndoors-Android-Examples/tree/main/MapBox/mapsindoorsgettingstartedbasicjava) or [Kotlin](https://github.com/MapsPe
Will fix when v2 and the guide app has been released

2023-08-14 12:39 UTC, matiasholst commented on docs/01-getting-started/flutter/search.mdx
> +See the full example of the search method here: [main.dart](example.com) //MADHTODO
Will fix when v2 and the guide app has been released

2023-08-14 12:39 UTC, matiasholst commented on docs/01-getting-started/flutter/search.mdx
> +The accompanying UI and implementation of this search experience can be found in the getting started app sample. [Getting Started App sample](https://github.com/MapsPeople/MapsIndoors-Android-Example
Will fix when v2 and the guide app has been released

2023-08-14 12:43 UTC, matiasholst commented on docs/01-getting-started/flutter/search.mdx
> +To be able to search we will use a text input field where a user can write what they want to search for. We can change the `AppBar` in our `Scaffold` to be the `SearchWidget` that we created earlier.
No, the appbar's title is changed to be a SearchWidget instead of a TextWidget

2023-08-15 12:46 UTC, matiasholst commented on docs/01-getting-started/flutter/map.mdx
> +
this has been added at the top of the file

2023-08-15 12:47 UTC, matiasholst commented on docs/01-getting-started/flutter/new-project.mdx
> +## Setup MapsIndoors
added link to setup for flutter project

2023-08-15 12:47 UTC, matiasholst commented on docs/01-getting-started/flutter/new-project.mdx
> +    //MADHTODO
added instructions

2023-08-15 12:47 UTC, matiasholst commented on docs/01-getting-started/flutter/map.mdx
> +<img src="/img/getting-started/android_map_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
added

2023-08-15 12:47 UTC, matiasholst commented on docs/01-getting-started/flutter/new-project.mdx
> +    //MADHTODO
added

2023-08-15 12:48 UTC, matiasholst commented on docs/01-getting-started/flutter/livedata.mdx
> +<img src="/img/getting-started/android_live_data_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
changed

2023-08-15 12:48 UTC, matiasholst commented on docs/01-getting-started/flutter/search.mdx
> +<img src="/img/getting-started/android_search_gif.gif" alt="An animation showing the desired behaviour of this tutorial" width="350"/>
changed

2023-08-15 12:48 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +We have already created a point in the basic example, called `_userPosition` to use as a starting point for directions on `MapState`
specified

2023-08-15 14:24 UTC, casm-mp requested changes

2023-08-15 14:24 UTC, casm-mp commented on docs/01-getting-started/flutter/index.md
> +title: Flutter
After going backwards through the guide I'm left with the following unexplained code:
```dart
//class MapsIndoorsDemoApp extends StatelessWidget {
      // 'gettingstarted' is an alias for the demo api key
      home: const Map(
        apiKey: 'gettingstarted',
      ),
    );
  }
}

//class _MapState extends State<Map> {
  // We use the scaffold to construct a drawer for search results, and a bottomsheet for location details
  final _scaffoldKey = GlobalKey<ScaffoldState>();
  PersistentBottomSheetController? _controller;

  // Initialize the floor selector s.t. it can be given to both mapcontrol and the mapwidget
  // (*) when using the default FloorSelector, this is not needed, but here it is present as an example of how to add an FloorSelector.
  final _floorSelectorWidget = MPDefaultFloorSelector();

  // List used to populate the search results drawer
  List<MPLocation> _searchResults = [];

  //@override
  //Widget build(BuildContext context) {
    //return Scaffold(
      key: _scaffoldKey,
      //body: Center( child: Column( mainAxisAlignment: MainAxisAlignment.start, children: <Widget>[ _mapControl = MapsIndoorsWidget(
              floorSelector: _floorSelectorWidget,
      //),],),),
    //);
  //}
//}
```
(some lines are commented out for context)

2023-08-16 07:23 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +      backgroundColor: Colors.red,
no, this adds information which is only useful for this part of the guide.
I can move the else part

2023-08-16 07:25 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +      _renderer.setRoute(route);
Yes it is repeated but I do not want to just dump the entire class in a single example

2023-08-16 07:28 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +    _currentIndex = min(index, _route.legs!.length - 1);
What part of it is weird? the getter ensures the value is >0 and the setter ensures the values is <length, two easy equations instead of a complex one.

2023-08-16 07:29 UTC, matiasholst commented on docs/01-getting-started/flutter/directions.mdx
> +class RouteHandler {
The only parts that are repeated are the ones where new functionality is added

2023-08-16 07:29 UTC, matiasholst commented on docs/01-getting-started/flutter/index.md
> +---
Open an internal ticket on this

2023-08-16 12:54 UTC, casm-mp commented on docs/01-getting-started/flutter/directions.mdx
> +      backgroundColor: Colors.red,
Line numbers seem to have gotten lost since the comment is "outdated", but it was referring to the else part

2023-08-17 08:50 UTC, casm-mp commented on docs/01-getting-started/flutter/directions.mdx
> +    _currentIndex = min(index, _route.legs!.length - 1);
I would just do it like this. Should be more obvious what is being done, and less that can go wrong in the future.
```suggestion
    return _currentIndex;
  }

  // ensure that the new index does not go out of bounds
  set currentIndex(int index) {
    _currentIndex = index.clamp(0, _route.legs!.length - 1);
```

2023-08-17 09:16 UTC, casm-mp approved these changes

2023-08-17 10:22 UTC, merged